language: node_js
node_js:
  - '4'
  - '6'
notifications:
  email: false
  slack:
    rooms:
      secure: dt9tlKj3FNEcOt0E87TQ0pWzr539AA5g40nBhlhjmeSEe21HDgaQ/o0Kh9376FiLLpxMHi2nrW9DDvzJgwWknKBEW5iuXi8x1q9IXm8XhwO7X2N2Tgyd3izilkU59BGg3fdbDjKmpLWQLXeVwO0cTxFdAOgZ2CjDV8vxJC6guB8wggoiLE6GwcCBLh7cNoAFlt6gbKecQhWv2/HvnWltk73KrG/eAFv6Ao4iu98AlLkq6c1ZQtgdwLRTd2X3HXyeSQSB/xQABOKU7UxHS1GUEcEcNS48BKqovGuYRONNa36hrF+8Hh8dZuvDcwkB+UkQZGNaWKNGPRvdhZG42hC7SdjTPPda6TcmMA/6EezLRNdW3ZPWKTgkedTnwVYJuAklPLdLyhX0+whMn8a2LGv1ujir7iRV0bUQycytUoDieeHXV8wyOix7lY9Pbbf77/OSS2VqXp2OmBm4QYO7gvl9NsvaeZ+fAuU68F0me4/0mF9EAlGpKkvhJM+bHw5h55a808WSI0nJFz8XIDdqgtQOAjObelxe7dGUI9LxHJ995SRGnr67m54JJZEVmmqfzjub4OmnI4OucVcmFimIhRh9MCb1LgQyPBmGzWPT11j2cRCeWW4f6JKGD3ZBoMuO8F3U1kee44moDOSTYBNnROin5aQqpHwZ7AtDRjbXYBGBZJA=
